config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :acceuil
  resources :jeux

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/figurine.rb
class Figurine < ApplicationRecord
  belongs_to :joueur
end

app/models/joueur.rb
class Joueur < ApplicationRecord
end

app/models/roue.rb
class Roue < ApplicationRecord
  belongs_to :joueur
end

app/controllers/acceuil_controller.rb
class AcceuilController < ApplicationController

  def index

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/jeux_controller.rb
class JeuxController < ApplicationController

  def new
    @figurine = Figurine.find(1)
    @joueur = Joueur.new
    @roue = Roue.new
  end
end

app/helpers/acceuil_helper.rb
module AcceuilHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jeux_helper.rb
module JeuxHelper
end

app/views/acceuil/index.html.erb
<h1>bienvenue</h1>
<%= link_to "Nouvelle Partie", new_jeux_path %>

app/views/jeux/new.html.erb
<h1>nouvelle partie</h1>
<div class="principale">
  <div class="figurine_gauche">

    <div class="figurine_J1G">
      <%# img de la figurine
      barre d'amelioration
      barre d'attaque(sur le coté) %>
      <%= @figurine.amelioration %>
      <%= @figurine.attaque %>
      <%= @figurine.degats %>
    </div>

    <div class="figurine_J2G">
      <%# img de la figurine
      barre d'amelioration
      barre d'attaque(sur le coté) %>
    </div>

  </div>

  <div class="joueurs">

    <div class="J1">
      <%# roue
      pv
      mur %>
      <%= @joueur.pv %>
      <%= @joueur.mur %>
    </div>

    <div class="J2">
       <%# roue
      pv
      mur %>
    </div>

  </div>

  <div class="figurine_droite">

    <div class="figurine_J1D">
      <%# img de la figurine
      barre d'amelioration
      barre d'attaque(sur le coté) %>
    </div>

    <div class="figurine_J2D">
      <%# img de la figurine
      barre d'amelioration
      barre d'attaque(sur le coté) %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Roulette</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>